### ISSUE TITLE
Consider Tiers of undercover clearance levels

### ISSUE THREAD

**Issue by FoxKilo** [1ncontinentia/Incon-Undercover#26]
Would it be possible, by adding extra markers and kit arrays, to allow access to different unit groups within an enemy faction? So for example if I was dressed as an infantryman, I wouldn't be allowed into HQs, airfields or "secret" places. However, if I dressed up as the faction's spec-ops unit or officer clothing, I would be allowed in those places but scrutinised more?

For those of us who run more complex ALiVE missions and 3-way wars this would really open up RP possibilities for us.

**Comment by 1ncontinentia** [comment]
Yeah that could be feasible. The uniforms would have to be user defined. What type of 3-way war are you referring to? Sure you're already aware but all-vs-all won't work all that well with incognito mode (dressed as an enemy) - just so you know.

**Comment by Will-Nichols** [comment]
The way we are doing this @1ncontinentia is we have an independent faction that is player run, a blufor faction that is player run and an AI opfor. The indy's and the blufor are working together and only the indy's have access to the incog script at this time.

**Comment by 1ncontinentia** [comment]
Ah yeah, that makes sense. But all-vs-all 3-way wars don't work at the moment (and probably never will!). Just to update on this, it's going to be in the next version but that could be some months depending on how my Arma involvement goes.

**Comment by 1ncontinentia** [comment]
So, this is more or less implemented with 960ebac. There are only two tiers -- regular and high security. Any more and that would probably require a significant re-think of the script or some performance cost. Still, this allows you to have normal bases and then extra important areas on top of those. You can make it so you aren't allowed to carry weapons in those areas or will attract attention if wearing items that aren't whitelisted. Also works on whitelisted vehicles. Any other requests related to this implimentation, feel free to open another ticket.
